source "https://rubygems.org"

gem 'github-pages', '>= 207', group: :jekyll_plugins

# Added at 2019-11-25 10:11:40 -0800 by jhoward:
gem "nokogiri", "< 1.10.9"
gem "jekyll", ">= 3.9.0"
gem "kramdown", ">= 2.3.0"
